### ISSUE TITLE
最新版本的workflow.json，配置了代理感觉还是有些问题

### ISSUE THREAD

**Issue by ayanamimcy** [TTNomi/awpark#4]
目前下载的release中的最新版本，但是worfklow.json的数据严重缺失，导致使用体验有问题

**Comment by sipt** [comment]
第一次打开先读本地，并在后台进行远程下载；后续检索时发现上次更新时间与当前时间间隔超过十分钟，就会再在后台拉取；
所以会有短暂延迟。

**Comment by ayanamimcy** [comment]
嗯嗯 后面发现了，一开始的延迟有点大还以为是bug呢。谢谢

2022年4月23日 下午11:09，sipt ***@***.******@***.***>> 写道：



第一次打开先读本地，并在后台进行远程下载；后续检索时发现上次更新时间与当前时间间隔超过十分钟，就会再在后台拉取；
所以会有短暂延迟。
